### ISSUE TITLE
Alt-click not opening existing note

### ISSUE THREAD

**Issue by FrakBT** [CoolSax98/NotesUNeedFixes#1]
Alt-clicking an item is a shortcut to open the existing note, or create a new one if there is no existing one.  However, alt-click is sometimes creating a new note when one already exists (instead of opening the existing one).  The problem only occurs on not-new Notes.

**Comment by FrakBT** [comment]
Alt-clicking an item is a shortcut to open the existing note, or create a new one if there is no existing one.  However, alt-click is sometimes creating a new note when one already exists (instead of opening the existing one).

**Comment by FrakBT** [comment]
Using code from 1/14/19.  Opened Currency tab, alt-clicked on the icon for 7th Legion Service Medal which should have opened the existing ITM-type Note, but it instead created a new one.

Don't know if it's related, but hovering over that same icon in the Currency tab does NOT show the tooltip, unlike hovering over the other Currency icons in the list that also have Notes.

**Comment by CoolSax98** [comment]
Fixed in latest update. Cleaned up the item links used for item indexes to guard against future updates where Blizzard may add additional fields to the link. Should be safe until they completely change the format.
