### ISSUE TITLE
Existing Notes appearing empty when opened

### ISSUE THREAD

**Issue by FrakBT** [CoolSax98/NotesUNeedFixes#5]
All Notes are correctly displaying their contents in the tooltip when hovered over, but when opened, some are empty, with 0 / 10010 in the bottom right corner (chars / capacity).

This means I am unable to update any of these Notes, nor copy the contents to a new Note.

Example: Note named "8.0.1 Stat Priorities".

**Comment by CoolSax98** [comment]
[NotesUNeed.txt](https://github.com/CoolSax98/NotesUNeedFixes/files/2752733/NotesUNeed.txt)

Updated notes file with clean copy of stat priorities
updated eroded cliffdweller note

**Comment by FrakBT** [comment]
Fixed!
